name: New contributor message

on:
  pull_request_target:
    types: [opened]

jobs:
  build:
    name: Hello new contributor
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: ''
          pr-message: |
            Hello ${{ github.event.pull_request.user.login }}! Thank you for your contribution!

            As this is your first contribution be sure to check out the checklist.

            We'll review shortly.

            Welcome!
