name: Release Action

on:
  push:
    tags:
      - 'v*.*.*'
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Parse Tag
      uses: actions/github-script@v6
      with:
        script: |
          const tag = context.ref.replace('refs\/tags\/', '')
          core.exportVariable('tag', tag)
    - name: Prepare changelog
      uses: actions/github-script@v6
      with:
        script: |
          const template = require('./.github/workflows/changelog.template.json')
          template["base_branches"] = ["${{ secrets.MAIN_BRANCH }}"]
          const fs = require('fs')
          fs.writeFileSync('./.github/workflows/changelog.json', JSON.stringify(template))
    - name: Run test
      run: mvn test
    - name: Publish
      run: |
        mvn deploy \
          --settings .settings.xml \
          -Denv.NEXUS_USERNAME=${{ secrets.NEXUS_USERNAME }} \
          -Denv.NEXUS_PASS=${{ secrets.NEXUS_PASS }} \
          -Denv.NEXUS_REPO_RELEASE=${{ secrets.NEXUS_REPO_RELEASE }} \
          -Dmaven.test.skip=true
    - name: Generate Changelog
      id: Changelog
      uses: mikepenz/release-changelog-builder-action@v1
      with:
        configuration: ".github/workflows/changelog.json"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.tag }}
        release_name: ${{ env.tag }}
        body: |
          ${{ steps.Changelog.outputs.changelog }}
        draft: false
        prerelease: false